#!/usr/bin/env groovy
@Library('JenkinsSharedLibrary') _

// =========== GLOBAL VARS ===========
def dockerRegistryIP
// =========== GLOBAL VARS ===========

node {
	def projectProperties = [
		[$class: 'BuildDiscarderProperty',strategy: [$class: 'LogRotator', numToKeepStr: '3']],
		disableConcurrentBuilds(),
		parameters([
			string(name: 'MAJOR_VERSION', description: '', defaultValue: "3", trim: true),
			string(name: 'MINOR_VERSION', description: '', defaultValue: "12-10", trim: true),
			string(name: 'GIT_BRANCH', description: 'UI Branch Name', defaultValue: "", trim: true),
			string(name: 'ENV', description: 'ENV Prop Name', defaultValue: "",trim: true),
			string(name: 'VM_IP', description: 'Plese provide IP', defaultValue: "10.0.3.32", trim: true),
			string(name: 'VM_SERVICE_ACCOUNT', description: 'Service Account User', defaultValue: "centos", trim: true),
			string(name: 'DOCKER_PRIVATE_REGISTRY_IP', description: 'Docker Private Registry', defaultValue: "10.0.31.225", trim: true)
		])
	]
	//projectProperties.add(pipelineTriggers([cron('H 21 * * *')]))

	properties(projectProperties)

	Utils utils = new Utils()

	try {
		// =========== USER DEFINED VARS ===========
		def workspacePath = pwd()
		def nodeHome = tool 'NodeJS_V8'
		env.PATH="${env.PATH}:${nodeHome}/bin"
		def uiRepoUrl = 'ssh://git@innersource.accenture.com/appq/demandplannerui.git'

		def artifactName = 'demandplannerui'
		def applicationDir = 'demandplannerui'
		def releasedVersion = "${MAJOR_VERSION}.${MINOR_VERSION}.${BUILD_NUMBER}"
		def branchName = "${GIT_BRANCH}"
		def serverIP = "${VM_IP}"
		dockerRegistryIP ="${DOCKER_PRIVATE_REGISTRY_IP}"
		def serviceAccount = "${VM_SERVICE_ACCOUNT}"
		// =========== USER DEFINED VARS ===========

		currentBuild.displayName = "${artifactName}.${releasedVersion}"
		echo "workspacePath: ${workspacePath}"

		if (!serverIP?.trim() || !GIT_BRANCH?.trim() || !ENV?.trim() || !serviceAccount?.trim() || !dockerRegistryIP?.trim() || !MAJOR_VERSION?.trim() || !MINOR_VERSION?.trim()) {
			currentBuild.result = 'FAILURE'
			error 'Missing required Build Parameters'
		}

		stage('Git Checkout') {
			utils.sourceCodeCheckout(applicationDir, branchName, uiRepoUrl)
		}

		stage('NPM Build') {
			//'demandplannerui_npmbuild' folder will have ng build generated 'dist' folder(To avoid putting 'dist' folder in  'demandplannerui').
			utils.npmBuild('demandplannerui_npmbuild', branchName, uiRepoUrl)
		}

		stage('SonarQube Analysis') { utils.uiCodeQualityAnalysis('demandplannerui_npmbuild', releasedVersion) }

		stage("SonarQube Quality Gate") { utils.processQualityGate() }

		stage('Docker Build') {
			utils.uiDockerBuild(applicationDir, artifactName, releasedVersion)
		}
		utils.pushImage(artifactName, releasedVersion, dockerRegistryIP)										// Push Image to Private Repository
		utils.removeImages(artifactName)  																		// To clean images created on Jenkins BOX

		stage("deploy to : ${serverIP}"){
			utils.stopContainer(artifactName, serverIP, serviceAccount)
			dockerClean(artifactName, serverIP, utils, serviceAccount)													// To clean images created on VM BOX
			deployImage(artifactName, releasedVersion, "${ENV}", serverIP, utils, dockerRegistryIP, serviceAccount)
			subjectText = "JENKINS Notification: Successful Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' on ${serverIP}"
			bodyText = """ <p>Successful: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}] on ${serverIP}':</p><p>Check console output at "<a href="${env.BUILD_URL}">${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>"</p>"""
			utils.sendEmailNotification(subjectText, bodyText)
		}

	}catch (error) {
		println error
		// If there was an exception thrown, the build failed
		// currentBuild.result = 'FAILURE'
		subjectText = "JENKINS Notification: FAILED Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
		bodyText = """ <p>FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p><p>Check console output at "<a href="${env.BUILD_URL}">${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>"</p>"""
		utils.sendEmailNotification(subjectText, bodyText)
		throw error
	}
}

//--------------------------------------------------------- Utility Methods START ---------------------------------------------------------
def dockerClean(artifactName, serverIP, utils, serviceAccount) {
	utils.removeDanglingImages(artifactName, serverIP, serviceAccount)
}

def deployImage(artifactName, releasedVersion, ENV, destinationIP, utils, dockerRegistryIP, serviceAccount) {
	utils.promoteUIToEnv(artifactName, releasedVersion, ENV, destinationIP, dockerRegistryIP, serviceAccount)
}
//--------------------------------------------------------- Utility Methods END ---------------------------------------------------------